# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'template.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 574)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setSpacing(60)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_peso = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_peso.sizePolicy().hasHeightForWidth())
        self.label_peso.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_peso.setFont(font)
        self.label_peso.setObjectName("label_peso")
        self.horizontalLayout_3.addWidget(self.label_peso)
        self.plainTextEdit_peso = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_peso.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_peso.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.plainTextEdit_peso.setFont(font)
        self.plainTextEdit_peso.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.plainTextEdit_peso.setAutoFillBackground(False)
        self.plainTextEdit_peso.setReadOnly(True)
        self.plainTextEdit_peso.setPlainText("")
        self.plainTextEdit_peso.setCenterOnScroll(False)
        self.plainTextEdit_peso.setObjectName("plainTextEdit_peso")
        self.horizontalLayout_3.addWidget(self.plainTextEdit_peso)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_param1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_param1.sizePolicy().hasHeightForWidth())
        self.label_param1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_param1.setFont(font)
        self.label_param1.setObjectName("label_param1")
        self.horizontalLayout.addWidget(self.label_param1)
        self.label_param2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_param2.sizePolicy().hasHeightForWidth())
        self.label_param2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_param2.setFont(font)
        self.label_param2.setObjectName("label_param2")
        self.horizontalLayout.addWidget(self.label_param2)
        self.label_param3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_param3.sizePolicy().hasHeightForWidth())
        self.label_param3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_param3.setFont(font)
        self.label_param3.setObjectName("label_param3")
        self.horizontalLayout.addWidget(self.label_param3)
        self.label_param4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_param4.sizePolicy().hasHeightForWidth())
        self.label_param4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_param4.setFont(font)
        self.label_param4.setObjectName("label_param4")
        self.horizontalLayout.addWidget(self.label_param4)
        self.label_param5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_param5.sizePolicy().hasHeightForWidth())
        self.label_param5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_param5.setFont(font)
        self.label_param5.setObjectName("label_param5")
        self.horizontalLayout.addWidget(self.label_param5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plainTextEdit_param1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_param1.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_param1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.plainTextEdit_param1.setFont(font)
        self.plainTextEdit_param1.setObjectName("plainTextEdit_param1")
        self.horizontalLayout_2.addWidget(self.plainTextEdit_param1)
        self.plainTextEdit_param3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_param3.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_param3.setSizePolicy(sizePolicy)
        self.plainTextEdit_param3.setObjectName("plainTextEdit_param3")
        self.horizontalLayout_2.addWidget(self.plainTextEdit_param3)
        self.plainTextEdit_param2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_param2.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_param2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.plainTextEdit_param2.setFont(font)
        self.plainTextEdit_param2.setObjectName("plainTextEdit_param2")
        self.horizontalLayout_2.addWidget(self.plainTextEdit_param2)
        self.plainTextEdit_param4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_param4.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_param4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.plainTextEdit_param4.setFont(font)
        self.plainTextEdit_param4.setObjectName("plainTextEdit_param4")
        self.horizontalLayout_2.addWidget(self.plainTextEdit_param4)
        self.plainTextEdit_param5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_param5.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_param5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.plainTextEdit_param5.setFont(font)
        self.plainTextEdit_param5.setObjectName("plainTextEdit_param5")
        self.horizontalLayout_2.addWidget(self.plainTextEdit_param5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(150)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_izq = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_izq.sizePolicy().hasHeightForWidth())
        self.pushButton_izq.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_izq.setFont(font)
        self.pushButton_izq.setObjectName("pushButton_izq")
        self.horizontalLayout_4.addWidget(self.pushButton_izq)
        self.pushButton_der = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_der.sizePolicy().hasHeightForWidth())
        self.pushButton_der.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_der.setFont(font)
        self.pushButton_der.setObjectName("pushButton_der")
        self.horizontalLayout_4.addWidget(self.pushButton_der)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_historial = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_historial.sizePolicy().hasHeightForWidth())
        self.label_historial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_historial.setFont(font)
        self.label_historial.setObjectName("label_historial")
        self.verticalLayout.addWidget(self.label_historial)
        self.plainTextEdit_terminal = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_terminal.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_terminal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextEdit_terminal.setFont(font)
        self.plainTextEdit_terminal.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit_terminal.setPlainText("")
        self.plainTextEdit_terminal.setObjectName("plainTextEdit_terminal")
        self.verticalLayout.addWidget(self.plainTextEdit_terminal)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.butoneraDigitos = QtWidgets.QGridLayout()
        self.butoneraDigitos.setSpacing(40)
        self.butoneraDigitos.setObjectName("butoneraDigitos")
        self.pushButton_digito3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_digito3.sizePolicy().hasHeightForWidth())
        self.pushButton_digito3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_digito3.setFont(font)
        self.pushButton_digito3.setObjectName("pushButton_digito3")
        self.butoneraDigitos.addWidget(self.pushButton_digito3, 0, 2, 1, 1)
        self.pushButton_digito6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_digito6.sizePolicy().hasHeightForWidth())
        self.pushButton_digito6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_digito6.setFont(font)
        self.pushButton_digito6.setObjectName("pushButton_digito6")
        self.butoneraDigitos.addWidget(self.pushButton_digito6, 1, 2, 1, 1)
        self.pushButton_digito2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_digito2.sizePolicy().hasHeightForWidth())
        self.pushButton_digito2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_digito2.setFont(font)
        self.pushButton_digito2.setObjectName("pushButton_digito2")
        self.butoneraDigitos.addWidget(self.pushButton_digito2, 0, 1, 1, 1)
        self.pushButton_digito0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_digito0.sizePolicy().hasHeightForWidth())
        self.pushButton_digito0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_digito0.setFont(font)
        self.pushButton_digito0.setObjectName("pushButton_digito0")
        self.butoneraDigitos.addWidget(self.pushButton_digito0, 3, 1, 1, 1)
        self.pushButton_digito5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_digito5.sizePolicy().hasHeightForWidth())
        self.pushButton_digito5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_digito5.setFont(font)
        self.pushButton_digito5.setObjectName("pushButton_digito5")
        self.butoneraDigitos.addWidget(self.pushButton_digito5, 1, 1, 1, 1)
        self.pushButton_digito7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_digito7.sizePolicy().hasHeightForWidth())
        self.pushButton_digito7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_digito7.setFont(font)
        self.pushButton_digito7.setObjectName("pushButton_digito7")
        self.butoneraDigitos.addWidget(self.pushButton_digito7, 2, 0, 1, 1)
        self.pushButton_digito1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_digito1.sizePolicy().hasHeightForWidth())
        self.pushButton_digito1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_digito1.setFont(font)
        self.pushButton_digito1.setObjectName("pushButton_digito1")
        self.butoneraDigitos.addWidget(self.pushButton_digito1, 0, 0, 1, 1)
        self.pushButton_digito8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_digito8.sizePolicy().hasHeightForWidth())
        self.pushButton_digito8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_digito8.setFont(font)
        self.pushButton_digito8.setObjectName("pushButton_digito8")
        self.butoneraDigitos.addWidget(self.pushButton_digito8, 2, 1, 1, 1)
        self.pushButton_digito4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_digito4.sizePolicy().hasHeightForWidth())
        self.pushButton_digito4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_digito4.setFont(font)
        self.pushButton_digito4.setObjectName("pushButton_digito4")
        self.butoneraDigitos.addWidget(self.pushButton_digito4, 1, 0, 1, 1)
        self.pushButton_digitoDEL = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_digitoDEL.sizePolicy().hasHeightForWidth())
        self.pushButton_digitoDEL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_digitoDEL.setFont(font)
        self.pushButton_digitoDEL.setObjectName("pushButton_digitoDEL")
        self.butoneraDigitos.addWidget(self.pushButton_digitoDEL, 3, 0, 1, 1)
        self.pushButton_digito9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_digito9.sizePolicy().hasHeightForWidth())
        self.pushButton_digito9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_digito9.setFont(font)
        self.pushButton_digito9.setObjectName("pushButton_digito9")
        self.butoneraDigitos.addWidget(self.pushButton_digito9, 2, 2, 1, 1)
        self.pushButton_digitoOK = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_digitoOK.sizePolicy().hasHeightForWidth())
        self.pushButton_digitoOK.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_digitoOK.setFont(font)
        self.pushButton_digitoOK.setObjectName("pushButton_digitoOK")
        self.butoneraDigitos.addWidget(self.pushButton_digitoOK, 3, 2, 1, 1)
        self.horizontalLayout_5.addLayout(self.butoneraDigitos)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_peso.setText(_translate("MainWindow", "Valor de la Balanza (gr)"))
        self.label_param1.setText(_translate("MainWindow", "Param1:"))
        self.label_param2.setText(_translate("MainWindow", "Param2:"))
        self.label_param3.setText(_translate("MainWindow", "Param3:"))
        self.label_param4.setText(_translate("MainWindow", "Param4:"))
        self.label_param5.setText(_translate("MainWindow", "Param5:"))
        self.pushButton_izq.setText(_translate("MainWindow", "Izquierda"))
        self.pushButton_der.setText(_translate("MainWindow", "Derecha"))
        self.label_historial.setText(_translate("MainWindow", "HIstorial de comandos:"))
        self.pushButton_digito3.setText(_translate("MainWindow", "3"))
        self.pushButton_digito6.setText(_translate("MainWindow", "6"))
        self.pushButton_digito2.setText(_translate("MainWindow", "2"))
        self.pushButton_digito0.setText(_translate("MainWindow", "0"))
        self.pushButton_digito5.setText(_translate("MainWindow", "5"))
        self.pushButton_digito7.setText(_translate("MainWindow", "7"))
        self.pushButton_digito1.setText(_translate("MainWindow", "1"))
        self.pushButton_digito8.setText(_translate("MainWindow", "8"))
        self.pushButton_digito4.setText(_translate("MainWindow", "4"))
        self.pushButton_digitoDEL.setText(_translate("MainWindow", "DEL"))
        self.pushButton_digito9.setText(_translate("MainWindow", "9"))
        self.pushButton_digitoOK.setText(_translate("MainWindow", "OK"))
